### ISSUE TITLE
holy moly ramachandran

### ISSUE THREAD

**Issue by sidney-pham** [quadrupleslap/classes#1]
your stupid 2nd tab never loads and shows me that damn flippy colour-changey box thingy!!! i want to see my timetable u know...

this is stupid 

_bye_

**Comment by quadrupleslap** [comment]
Try _logging in_. It helps. yw
And yes, the loader will eventually be replaced with a login button.
I might eventually get rid of the loader because the site is too fast. :wink:

**Comment by dallasyan** [comment]
Yeah me too

**Comment by sidney-pham** [comment]
Grounds for closure extremely debatable, but I guess we have no choice but to obey our dictator.

**Comment by sidney-pham** [comment]
In particular, you haven't addressed:

- > this is stupid
